# Generated by Django 3.1.5 on 2021-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_sanitized',
            field=models.TextField(blank=True),
        ),
    ]
