# Generated by Django 3.1.4 on 2021-01-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20210102_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='things.profile', to_field='user'),
            preserve_default=False,
        ),
    ]
