# Generated by Django 3.1.5 on 2021-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_post_title_sanitized'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
