# Generated by Django 3.1.4 on 2021-01-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20210113_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(related_name='_comment_comments_+', to='things.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='post', to='things.Comment'),
        ),
    ]
