# Generated by Django 3.1.4 on 2021-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_post_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(related_name='user_votes', to='things.Vote'),
        ),
    ]
