# Generated by Django 3.1.4 on 2021-01-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_auto_20210113_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='subcomments',
            field=models.ManyToManyField(related_name='_comment_subcomments_+', to='things.Comment'),
        ),
    ]
