# Generated by Django 3.1.4 on 2021-01-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
