# Generated by Django 3.1.4 on 2021-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_auto_20210117_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subcomments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(related_name='_comment_comments_+', to='things.Comment'),
        ),
    ]
