# Generated by Django 3.1.4 on 2021-01-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_auto_20210117_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='sub_comments',
            field=models.ManyToManyField(related_name='comments', to='things.Comment'),
        ),
    ]
