# Generated by Django 3.1.4 on 2021-01-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_remove_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(related_name='post_votes', to='things.Vote'),
        ),
    ]
