# Generated by Django 3.1.4 on 2021-01-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_auto_20210117_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sub_comments',
            new_name='comments_field',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='comments_field',
        ),
    ]
